// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzdlsGDrliV2DgCi6_swh6zE1EnGybqVg',
    appId: '1:1062445059668:web:e01ca91351aece0e80a7c1',
    messagingSenderId: '1062445059668',
    projectId: 'quizz-app-4e6e6',
    authDomain: 'quizz-app-4e6e6.firebaseapp.com',
    storageBucket: 'quizz-app-4e6e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRSrLLagIUg4lHnhWEGyJ-E882jgkMw7I',
    appId: '1:1062445059668:android:cf975ec58c564e3680a7c1',
    messagingSenderId: '1062445059668',
    projectId: 'quizz-app-4e6e6',
    storageBucket: 'quizz-app-4e6e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsSaNpfwD3yV1exqXeDGwF8NiHqifkmyA',
    appId: '1:1062445059668:ios:843dca4b89e1f9b880a7c1',
    messagingSenderId: '1062445059668',
    projectId: 'quizz-app-4e6e6',
    storageBucket: 'quizz-app-4e6e6.appspot.com',
    iosClientId: '1062445059668-4pvs1ndscrui042qfkgu85qua5v50vac.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzAppWithFirebaseDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsSaNpfwD3yV1exqXeDGwF8NiHqifkmyA',
    appId: '1:1062445059668:ios:843dca4b89e1f9b880a7c1',
    messagingSenderId: '1062445059668',
    projectId: 'quizz-app-4e6e6',
    storageBucket: 'quizz-app-4e6e6.appspot.com',
    iosClientId: '1062445059668-4pvs1ndscrui042qfkgu85qua5v50vac.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzAppWithFirebaseDb',
  );
}
